name: automerge check

on:
  workflow_call:
    inputs:
      merge_labels:
        type: string
        default: ':rocket: Ready to Merge,!:warning: Blocked,!:earth_africa: i18n needed,!:busts_in_silhouette: Panel Review Needed,!Development in progress,!:eyes: Design Review Needed,!:eyes: Func Review Needed,!:eyes: Tech Review Needed'
      merge_commit_message: 
        type: string
        default: pull-request-title
      update_labels: 
        type: string
        default: ':rocket: Ready to Merge'
      update_method: 
        type: string
        default: rebase
      merge_forks: 
        type: string
        default: 'false'
    secrets:
      auto_merge_token:
        required: true

jobs:
  automerge:
    if: >
      ${{ contains(github.event.pull_request.labels.*.name, inputs.update_labels) }}
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: '${{ secrets.auto_merge_token }}'
          MERGE_LABELS: '${{ inputs.merge_labels }}'
          MERGE_COMMIT_MESSAGE: '${{ inputs.merge_commit_message }}'
          UPDATE_LABELS: '${{ inputs.update_labels }}'
          UPDATE_METHOD: '${{ inputs.update_method }}'
          MERGE_FORKS: '${{ inputs.merge_forks }}'
