name: automerge check

on:
  pull_request:
    types:
      - labeled
      - unlabeled
  check_suite:
    types:
      - completed
  status:
    types:
      - success

jobs:
  automerge:
    steps:
      - uses: 1024pix/pix-actions/auto-merge@6575d94a9672fa3573470a1bed8e7dce0315f60f
        with:
          auto_merge_token: "${{ secrets.PIX_SERVICE_ACTIONS_TOKEN }}"
