name: automerge check

on:
  workflow_dispatch:
    inputs:
      pullRequest:
        description: 'Pull request préfixé par le nom du repo : 1024pix/pix'
        required: true


inputs:
  auto_merge_token:
    required: true
  merge_labels:
    type: string
    default: ':rocket: Ready to Merge,!:warning: Blocked,!:earth_africa: i18n needed,!:busts_in_silhouette: Panel Review Needed,!Development in progress,!:eyes: Design Review Needed,!:eyes: Func Review Needed,!:eyes: Tech Review Needed'
  merge_commit_message:
    type: string
    default: "{pullRequest.title} \n\n #{pullRequest.number}"
  update_labels:
    type: string
    default: ':rocket: Ready to Merge'
  update_method:
    type: string
    default: rebase
  merge_forks:
    type: string
    default: 'false'

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: | 
          echo '${{ input.pull_request }}'
#      - name: automerge
#        uses: pascalgn/automerge-action@v0.16.4
#        env:
#          GITHUB_TOKEN: '${{ inputs.auto_merge_token }}'
#          MERGE_LABELS: '${{ inputs.merge_labels }}'
#          MERGE_COMMIT_MESSAGE: '${{ inputs.merge_commit_message }}'
#          UPDATE_LABELS: '${{ inputs.update_labels }}'
#          UPDATE_METHOD: '${{ inputs.update_method }}'
#          MERGE_FORKS: '${{ inputs.merge_forks }}'
#          PULL_REQUEST: '${{ inputs.pullRequest }}'

